spring:
  application:
    name: cbu-plugin
  data:
    jdbc:
      dialect: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/cbu_db
    driverClassName: org.postgresql.Driver
    username: cbu
    password: cbu123
  liquibase:
    change-log: classpath:db/master.xml
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

server:
  port: 8081

cbu:
  setting:
    base-url: https://cbu.uz
    simulate: impl
  client-config:
    connection-timeout: 5000
    read-timeout: 5000
