spring:
  application:
    name: cbu-plugin
  data:
    jdbc:
      dialect: postgresql
  datasource:
    username: cbu
    password: cbu123
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/cbu_db

  jpa:
    hibernate:
      ddl-auto: update

cbu:
  setting:
    base-url: https://cbu.uz
    simulate: impl
  client-config:
    connection-timeout: 5000
    read-timeout: 5000
